# Generated by Django 3.2.4 on 2021-06-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoctorsPortal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblPatientDetails',
            fields=[
                ('patientId', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default='')),
                ('mobile', models.IntegerField(default='')),
                ('place', models.CharField(default='', max_length=100)),
                ('intCreatedUserId', models.IntegerField(default='')),
                ('dattimeCreated', models.DateTimeField()),
                ('intLastAction', models.IntegerField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbluser',
            name='id',
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='userId',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
